### ISSUE TITLE
direct link to a tab ?

### ISSUE THREAD

**Issue by ferreol** [perfwatcher/perfwatcher#57]
Hi,

is there a way to have direct URL to a tab ?

http://machine/perfwatcher/#id_1_2_6 allows me just to go through the tree

regards,

Ferréol

**Comment by ymettier** [comment]
Hello,

There are 2 URLs to a tab : 
http://machine/perfwatcher/#host_SERVER/TAB
http://machine/perfwatcher/#host_/SOURCE/SERVER/TAB

...where you want to replace SERVER with the server name, and TAB with the tab name. Example with a server named `gandalf` :
http://machine/perfwatcher/#host_gandalf/memory

If you need to specify the Collectd source (if you have more than one Collectd concentrators), replace SOURCE with the source you want (see what you set in your etc/config.php). Same example with Collectd source named SRC1 :
http://machine/perfwatcher/#host_/SRC1/gandalf/memory

## Remarks

When you change the end of the URL (I mean what is after the #), you need to reload the page (with F5 or "reload" or click on the "reload" button) in order to see the tab. This is because you do not change the URL itself and your web browser will not reload when you do not change the URL.
This is not a bug. And we do not like this behaviour. So in the future, there may be another URL (REST API ?).
This is why the #host_SERVER/TAB and #host_/SOURCE/SERVER/TAB is not documented : we want to be able to change it one day.

Currently there is no direct URL to a tab http://machine/perfwatcher/#id_1_2_6/TAB.
I think that this would be easy to code if someone wants to give a try.

Regards

**Comment by ferreol** [comment]
I got it working with http://machine/perfwatcher/#host_gandalf/memory

however, I want to point to a tab in a custom "Container" whithin a "Folder ". is there a shorcut for this ?

**Comment by ymettier** [comment]
Hello,

> however, I want to point to a tab in a custom "Container" whithin a "Folder ". is there a shorcut for this ?

As I said at the end of my previous comment, no, there is not. But it should be easy to implement.

Regards,
Yves

**Comment by ymettier** [comment]
http://machine/perfwatcher/#id_1_2_6/memory will move you to the "memory" tab.

I hope I can release perfwatcher-2.2.4 soon.

Regards,
Yves
